### ISSUE TITLE
[Fix] QNG optimizer not compatible with qadence training function

### ISSUE THREAD

**Issue by DanieleCucurachi** [pasqal-io/qadence-libs#21]
# Description 

[QNG](https://github.com/pasqal-io/qadence-libs/blob/v0.1.2/qadence_libs/qinfo_tools/qng.py) has been recently added to `qinfo_tools`. While it works smoothly with simple training loops, as shown [here](https://github.com/pasqal-io/qadence-libs/blob/v0.1.2/docs/qinfo_tools/qng.md), it is not compatible with [`train()`](https://github.com/pasqal-io/qadence/blob/main/qadence/ml_tools/train_grad.py), function defined in `qadence` to automate the definition of the training process with gradient-based optimizers. 

In particular, the error seems to be related to Python's pickle module having trouble pickling a local object:
```
Traceback (most recent call last):
  File ".../qadence/ml_tools/saveload.py", line 76, in write_checkpoint
    torch.save(
  File ".../torch/serialization.py", line 628, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File ".../torch/serialization.py", line 840, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'Parametric.__init__.<locals>.parse_values'
```

**Comment by inafergra** [comment]
Thanks for finding this @DanieleCucurachi. As discussed, I believe the issue is in the serialization of the optimizers `state_dict`, as the QNG's `state_dict` holds a quantum circuit. We probably need to add some logic to correctly serialize it. I will take a look into it

**Comment by RolandMacDoland** [comment]
@DanieleCucurachi @inafergra Is this a duplicate from https://github.com/pasqal-io/qadence-hub/issues/103 ?

**Comment by inafergra** [comment]
> [@DanieleCucurachi](https://github.com/DanieleCucurachi) [@inafergra](https://github.com/inafergra) Is this a duplicate from [#23](https://github.com/pasqal-io/qadence-hub/issues/103) ?

Hey @RolandMacDoland I don't think so, in fact I think this issue was already solved in pasqal-io/qadence-libs#22 so we can close it. Issue pasqal-io/qadence-hub#103 is not solved yet I believe
